export const GET_CURRENCY_RATES = 'GET_CURRENCY_RATES';
export const GET_CURRENCY_RATES_COMPLETE = 'GET_CURRENCY_RATES_COMPLETE';
export const GET_CURRENCY_RATES_FAIL = 'GET_CURRENCY_RATES_FAIL';

export const CHANGE_SYMBOL = 'CHANGE_SYMBOL';

export const GET_SYMBOLS = 'GET_SYMBOLS';
export const GET_SYMBOLS_COMPLETE = 'GET_SYMBOLS_COMPLETE';
export const GET_SYMBOLS_FAIL = 'GET_SYMBOLS_FAIL';
